"""initial schema

Revision ID: 8fddfd9e0ab8
Revises:
Create Date: 2026-02-10 04:44:05.896412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8fddfd9e0ab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('entity_type', sa.String(length=50), nullable=False),
                    sa.Column('entity_id', sa.String(length=50), nullable=False),
                    sa.Column('action', sa.String(length=20), nullable=False),
                    sa.Column('old_data', sa.JSON(), nullable=True),
                    sa.Column('new_data', sa.JSON(), nullable=True),
                    sa.Column('details', sa.Text(), nullable=True),
                    sa.Column('user_id', sa.String(length=50), nullable=True),
                    sa.Column('username', sa.String(length=100), nullable=True),
                    sa.Column('ip_address', sa.String(length=50), nullable=True),
                    sa.Column('user_agent', sa.Text(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action', 'timestamp'], unique=False)
    op.create_index('ix_audit_logs_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_logs_ip', 'audit_logs', ['ip_address'], unique=False)
    op.create_index('ix_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    op.create_table('battery_cell_readings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('cell_voltages', sa.JSON(), nullable=True),
                    sa.Column('min_voltage', sa.Float(), nullable=True),
                    sa.Column('max_voltage', sa.Float(), nullable=True),
                    sa.Column('avg_voltage', sa.Float(), nullable=True),
                    sa.Column('voltage_delta', sa.Float(), nullable=True),
                    sa.Column('module1_avg', sa.Float(), nullable=True),
                    sa.Column('module2_avg', sa.Float(), nullable=True),
                    sa.Column('module3_avg', sa.Float(), nullable=True),
                    sa.Column('ambient_temp_f', sa.Float(), nullable=True),
                    sa.Column('state_of_charge', sa.Float(), nullable=True),
                    sa.Column('is_charging', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_battery_cell_readings_timestamp'), 'battery_cell_readings', ['timestamp'], unique=False)
    op.create_table('battery_health_readings',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('capacity_kwh', sa.Float(), nullable=True),
                    sa.Column('normalized_capacity_kwh', sa.Float(), nullable=True),
                    sa.Column('soc_at_reading', sa.Float(), nullable=True),
                    sa.Column('ambient_temp_f', sa.Float(), nullable=True),
                    sa.Column('odometer_miles', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_battery_health_readings_timestamp'),
                    'battery_health_readings', ['timestamp'], unique=False)
    op.create_table('charging_hourly_stats',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('hour_timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('total_sessions', sa.Integer(), nullable=True),
                    sa.Column('l1_sessions', sa.Integer(), nullable=True),
                    sa.Column('l2_sessions', sa.Integer(), nullable=True),
                    sa.Column('dcfc_sessions', sa.Integer(), nullable=True),
                    sa.Column('completed_sessions', sa.Integer(), nullable=True),
                    sa.Column('total_kwh_added', sa.Float(), nullable=True),
                    sa.Column('avg_kwh_per_session', sa.Float(), nullable=True),
                    sa.Column('avg_peak_power_kw', sa.Float(), nullable=True),
                    sa.Column('avg_avg_power_kw', sa.Float(), nullable=True),
                    sa.Column('avg_start_soc', sa.Float(), nullable=True),
                    sa.Column('avg_end_soc', sa.Float(), nullable=True),
                    sa.Column('avg_soc_gained', sa.Float(), nullable=True),
                    sa.Column('avg_session_duration', sa.Float(), nullable=True),
                    sa.Column('total_charging_minutes', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('hour_timestamp')
                    )
    op.create_table('charging_sessions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('start_soc', sa.Float(), nullable=True),
                    sa.Column('end_soc', sa.Float(), nullable=True),
                    sa.Column('kwh_added', sa.Float(), nullable=True),
                    sa.Column('peak_power_kw', sa.Float(), nullable=True),
                    sa.Column('avg_power_kw', sa.Float(), nullable=True),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('location_name', sa.String(length=255), nullable=True),
                    sa.Column('charge_type', sa.String(length=50), nullable=True),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.Column('cost_per_kwh', sa.Float(), nullable=True),
                    sa.Column('electricity_rate', sa.Float(), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('charging_curve', sa.JSON(), nullable=True),
                    sa.Column('is_complete', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('start_time', name='uq_charging_session_start_time')
                    )
    op.create_index(op.f('ix_charging_sessions_is_complete'), 'charging_sessions', ['is_complete'], unique=False)
    op.create_index('ix_charging_sessions_is_complete_start_time',
                    'charging_sessions', ['is_complete', 'start_time'], unique=False)
    op.create_index(op.f('ix_charging_sessions_start_time'), 'charging_sessions', ['start_time'], unique=False)
    op.create_table('fuel_events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('odometer_miles', sa.Float(), nullable=True),
                    sa.Column('gallons_added', sa.Float(), nullable=True),
                    sa.Column('fuel_level_before', sa.Float(), nullable=True),
                    sa.Column('fuel_level_after', sa.Float(), nullable=True),
                    sa.Column('price_per_gallon', sa.Float(), nullable=True),
                    sa.Column('total_cost', sa.Float(), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_fuel_events_timestamp'), 'fuel_events', ['timestamp'], unique=False)
    op.create_table('maintenance_records',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('maintenance_type', sa.String(length=100), nullable=False),
                    sa.Column('service_date', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('odometer_miles', sa.Float(), nullable=True),
                    sa.Column('engine_hours', sa.Float(), nullable=True),
                    sa.Column('cost', sa.Float(), nullable=True),
                    sa.Column('location', sa.String(length=200), nullable=True),
                    sa.Column('notes', sa.Text(), nullable=True),
                    sa.Column('next_due_date', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('next_due_miles', sa.Float(), nullable=True),
                    sa.Column('next_due_engine_hours', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_maintenance_records_service_date'), 'maintenance_records', ['service_date'], unique=False)
    op.create_index('ix_maintenance_type_date', 'maintenance_records',
                    ['maintenance_type', 'service_date'], unique=False)
    op.create_table('monthly_summary',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('year', sa.Integer(), nullable=False),
                    sa.Column('month', sa.Integer(), nullable=False),
                    sa.Column('total_trips', sa.Integer(), nullable=True),
                    sa.Column('total_distance_miles', sa.Float(), nullable=True),
                    sa.Column('total_electric_miles', sa.Float(), nullable=True),
                    sa.Column('total_gas_miles', sa.Float(), nullable=True),
                    sa.Column('electric_percentage', sa.Float(), nullable=True),
                    sa.Column('avg_kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('avg_mpg', sa.Float(), nullable=True),
                    sa.Column('total_kwh_used', sa.Float(), nullable=True),
                    sa.Column('total_gallons_used', sa.Float(), nullable=True),
                    sa.Column('total_charging_sessions', sa.Integer(), nullable=True),
                    sa.Column('total_kwh_charged', sa.Float(), nullable=True),
                    sa.Column('l1_sessions', sa.Integer(), nullable=True),
                    sa.Column('l2_sessions', sa.Integer(), nullable=True),
                    sa.Column('dcfc_sessions', sa.Integer(), nullable=True),
                    sa.Column('estimated_electricity_cost', sa.Float(), nullable=True),
                    sa.Column('estimated_gas_cost', sa.Float(), nullable=True),
                    sa.Column('co2_avoided_lbs', sa.Float(), nullable=True),
                    sa.Column('avg_temp_f', sa.Float(), nullable=True),
                    sa.Column('extreme_weather_trips', sa.Integer(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('year', 'month', name='uq_monthly_year_month')
                    )
    op.create_table('routes',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=200), nullable=True),
                    sa.Column('start_lat', sa.Float(), nullable=False),
                    sa.Column('start_lon', sa.Float(), nullable=False),
                    sa.Column('end_lat', sa.Float(), nullable=False),
                    sa.Column('end_lon', sa.Float(), nullable=False),
                    sa.Column('trip_count', sa.Integer(), nullable=True),
                    sa.Column('avg_distance_miles', sa.Float(), nullable=True),
                    sa.Column('avg_efficiency_kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('avg_duration_minutes', sa.Float(), nullable=True),
                    sa.Column('best_efficiency', sa.Float(), nullable=True),
                    sa.Column('worst_efficiency', sa.Float(), nullable=True),
                    sa.Column('last_traveled', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('elevation_profile', sa.JSON(), nullable=True),
                    sa.Column('avg_elevation_gain_m', sa.Float(), nullable=True),
                    sa.Column('avg_elevation_loss_m', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('telemetry_raw',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('session_id', sa.String(length=36), nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('latitude', sa.Float(), nullable=True),
                    sa.Column('longitude', sa.Float(), nullable=True),
                    sa.Column('speed_mph', sa.Float(), nullable=True),
                    sa.Column('engine_rpm', sa.Float(), nullable=True),
                    sa.Column('throttle_position', sa.Float(), nullable=True),
                    sa.Column('coolant_temp_f', sa.Float(), nullable=True),
                    sa.Column('intake_air_temp_f', sa.Float(), nullable=True),
                    sa.Column('fuel_level_percent', sa.Float(), nullable=True),
                    sa.Column('fuel_remaining_gallons', sa.Float(), nullable=True),
                    sa.Column('state_of_charge', sa.Float(), nullable=True),
                    sa.Column('battery_voltage', sa.Float(), nullable=True),
                    sa.Column('ambient_temp_f', sa.Float(), nullable=True),
                    sa.Column('odometer_miles', sa.Float(), nullable=True),
                    sa.Column('hv_battery_power_kw', sa.Float(), nullable=True),
                    sa.Column('hv_battery_current_a', sa.Float(), nullable=True),
                    sa.Column('hv_battery_voltage_v', sa.Float(), nullable=True),
                    sa.Column('hv_discharge_amps', sa.Float(), nullable=True),
                    sa.Column('battery_temp_f', sa.Float(), nullable=True),
                    sa.Column('battery_coolant_temp_f', sa.Float(), nullable=True),
                    sa.Column('charger_ac_power_kw', sa.Float(), nullable=True),
                    sa.Column('charger_connected', sa.Boolean(), nullable=True),
                    sa.Column('charger_status', sa.Float(), nullable=True),
                    sa.Column('charger_power_kw', sa.Float(), nullable=True),
                    sa.Column('charger_power_w', sa.Float(), nullable=True),
                    sa.Column('charger_ac_voltage', sa.Float(), nullable=True),
                    sa.Column('charger_ac_current', sa.Float(), nullable=True),
                    sa.Column('charger_hv_voltage', sa.Float(), nullable=True),
                    sa.Column('charger_hv_current', sa.Float(), nullable=True),
                    sa.Column('last_charge_wh', sa.Float(), nullable=True),
                    sa.Column('motor_a_rpm', sa.Float(), nullable=True),
                    sa.Column('motor_b_rpm', sa.Float(), nullable=True),
                    sa.Column('generator_rpm', sa.Float(), nullable=True),
                    sa.Column('motor_temp_max_f', sa.Float(), nullable=True),
                    sa.Column('engine_oil_temp_f', sa.Float(), nullable=True),
                    sa.Column('engine_torque_nm', sa.Float(), nullable=True),
                    sa.Column('engine_running', sa.Boolean(), nullable=True),
                    sa.Column('transmission_temp_f', sa.Float(), nullable=True),
                    sa.Column('battery_capacity_kwh', sa.Float(), nullable=True),
                    sa.Column('lifetime_ev_miles', sa.Float(), nullable=True),
                    sa.Column('lifetime_gas_miles', sa.Float(), nullable=True),
                    sa.Column('lifetime_fuel_gal', sa.Float(), nullable=True),
                    sa.Column('lifetime_kwh', sa.Float(), nullable=True),
                    sa.Column('dte_electric_miles', sa.Float(), nullable=True),
                    sa.Column('dte_gas_miles', sa.Float(), nullable=True),
                    sa.Column('elevation_meters', sa.Float(), nullable=True),
                    sa.Column('raw_data', sa.JSON(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_telemetry_raw_engine_rpm'), 'telemetry_raw', ['engine_rpm'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_session_id'), 'telemetry_raw', ['session_id'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_state_of_charge'), 'telemetry_raw', ['state_of_charge'], unique=False)
    op.create_index(op.f('ix_telemetry_raw_timestamp'), 'telemetry_raw', ['timestamp'], unique=False)
    op.create_index('ix_telemetry_session_timestamp', 'telemetry_raw', ['session_id', 'timestamp'], unique=False)
    op.create_table('trip_daily_stats',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('date', sa.Date(), nullable=False),
                    sa.Column('total_trips', sa.Integer(), nullable=True),
                    sa.Column('ev_only_trips', sa.Integer(), nullable=True),
                    sa.Column('gas_mode_trips', sa.Integer(), nullable=True),
                    sa.Column('extreme_weather_trips', sa.Integer(), nullable=True),
                    sa.Column('total_distance_miles', sa.Float(), nullable=True),
                    sa.Column('total_electric_miles', sa.Float(), nullable=True),
                    sa.Column('total_gas_miles', sa.Float(), nullable=True),
                    sa.Column('avg_trip_distance', sa.Float(), nullable=True),
                    sa.Column('avg_kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('best_kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('worst_kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('avg_mpg', sa.Float(), nullable=True),
                    sa.Column('total_elevation_gain_m', sa.Float(), nullable=True),
                    sa.Column('avg_elevation_gain_m', sa.Float(), nullable=True),
                    sa.Column('avg_temp_f', sa.Float(), nullable=True),
                    sa.Column('min_temp_f', sa.Float(), nullable=True),
                    sa.Column('max_temp_f', sa.Float(), nullable=True),
                    sa.Column('avg_wind_mph', sa.Float(), nullable=True),
                    sa.Column('total_precipitation_in', sa.Float(), nullable=True),
                    sa.Column('avg_speed_mph', sa.Float(), nullable=True),
                    sa.Column('max_speed_mph', sa.Float(), nullable=True),
                    sa.Column('total_kwh_used', sa.Float(), nullable=True),
                    sa.Column('avg_weather_impact_factor', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('date')
                    )
    op.create_table('trips',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('session_id', sa.String(length=36), nullable=False),
                    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('start_odometer', sa.Float(), nullable=True),
                    sa.Column('end_odometer', sa.Float(), nullable=True),
                    sa.Column('distance_miles', sa.Float(), nullable=True),
                    sa.Column('start_soc', sa.Float(), nullable=True),
                    sa.Column('soc_at_gas_transition', sa.Float(), nullable=True),
                    sa.Column('electric_miles', sa.Float(), nullable=True),
                    sa.Column('electric_kwh_used', sa.Float(), nullable=True),
                    sa.Column('kwh_per_mile', sa.Float(), nullable=True),
                    sa.Column('gas_mode_entered', sa.Boolean(), nullable=True),
                    sa.Column('gas_mode_entry_time', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('gas_miles', sa.Float(), nullable=True),
                    sa.Column('fuel_used_gallons', sa.Float(), nullable=True),
                    sa.Column('gas_mpg', sa.Float(), nullable=True),
                    sa.Column('fuel_level_at_gas_entry', sa.Float(), nullable=True),
                    sa.Column('fuel_level_at_end', sa.Float(), nullable=True),
                    sa.Column('ambient_temp_avg_f', sa.Float(), nullable=True),
                    sa.Column('is_closed', sa.Boolean(), nullable=True),
                    sa.Column('is_imported', sa.Boolean(), nullable=True),
                    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('weather_temp_f', sa.Float(), nullable=True),
                    sa.Column('weather_precipitation_in', sa.Float(), nullable=True),
                    sa.Column('weather_wind_mph', sa.Float(), nullable=True),
                    sa.Column('weather_conditions', sa.String(length=50), nullable=True),
                    sa.Column('weather_impact_factor', sa.Float(), nullable=True),
                    sa.Column('extreme_weather', sa.Boolean(), nullable=True),
                    sa.Column('elevation_start_m', sa.Float(), nullable=True),
                    sa.Column('elevation_end_m', sa.Float(), nullable=True),
                    sa.Column('elevation_gain_m', sa.Float(), nullable=True),
                    sa.Column('elevation_loss_m', sa.Float(), nullable=True),
                    sa.Column('elevation_net_change_m', sa.Float(), nullable=True),
                    sa.Column('elevation_max_m', sa.Float(), nullable=True),
                    sa.Column('elevation_min_m', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('session_id')
                    )
    op.create_index('ix_trips_closed_deleted_time', 'trips', ['is_closed', 'deleted_at', 'start_time'], unique=False)
    op.create_index(op.f('ix_trips_deleted_at'), 'trips', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_trips_gas_mode_entered'), 'trips', ['gas_mode_entered'], unique=False)
    op.create_index('ix_trips_gas_mode_start_time', 'trips', ['gas_mode_entered', 'start_time'], unique=False)
    op.create_index(op.f('ix_trips_is_closed'), 'trips', ['is_closed'], unique=False)
    op.create_index('ix_trips_is_closed_start_time', 'trips', ['is_closed', 'start_time'], unique=False)
    op.create_index(op.f('ix_trips_is_imported'), 'trips', ['is_imported'], unique=False)
    op.create_index(op.f('ix_trips_start_time'), 'trips', ['start_time'], unique=False)
    op.create_table('weather_cache',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('latitude_key', sa.Float(), nullable=False),
                    sa.Column('longitude_key', sa.Float(), nullable=False),
                    sa.Column('timestamp_hour', sa.String(length=16), nullable=False),
                    sa.Column('temperature_f', sa.Float(), nullable=True),
                    sa.Column('precipitation_in', sa.Float(), nullable=True),
                    sa.Column('wind_speed_mph', sa.Float(), nullable=True),
                    sa.Column('weather_code', sa.Integer(), nullable=True),
                    sa.Column('conditions', sa.String(length=50), nullable=True),
                    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('api_source', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('latitude_key', 'longitude_key', 'timestamp_hour', name='uq_weather_cache_key')
                    )
    op.create_index('ix_weather_cache_fetched_at', 'weather_cache', ['fetched_at'], unique=False)
    op.create_index('ix_weather_cache_lookup', 'weather_cache', [
                    'latitude_key', 'longitude_key', 'timestamp_hour'], unique=False)
    op.create_table('web_vitals',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('value', sa.Float(), nullable=False),
                    sa.Column('rating', sa.String(length=20), nullable=True),
                    sa.Column('metric_id', sa.String(length=100), nullable=True),
                    sa.Column('navigation_type', sa.String(length=50), nullable=True),
                    sa.Column('url', sa.String(length=500), nullable=True),
                    sa.Column('user_agent', sa.Text(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index('ix_web_vitals_name_timestamp', 'web_vitals', ['name', 'timestamp'], unique=False)
    op.create_index('ix_web_vitals_rating', 'web_vitals', ['rating'], unique=False)
    op.create_index(op.f('ix_web_vitals_timestamp'), 'web_vitals', ['timestamp'], unique=False)
    op.create_table('csv_imports',
                    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('import_code', sa.String(length=20), nullable=False),
                    sa.Column('filename', sa.String(length=255), nullable=False),
                    sa.Column('file_hash', sa.String(length=64), nullable=False),
                    sa.Column('file_size_bytes', sa.Integer(), nullable=False),
                    sa.Column('status', sa.String(length=20), nullable=False),
                    sa.Column('failure_reason', sa.String(length=100), nullable=True),
                    sa.Column('failure_details', sa.JSON(), nullable=True),
                    sa.Column('suggestion', sa.Text(), nullable=True),
                    sa.Column('total_rows', sa.Integer(), nullable=True),
                    sa.Column('parsed_rows', sa.Integer(), nullable=True),
                    sa.Column('skipped_rows', sa.Integer(), nullable=True),
                    sa.Column('duplicate_rows', sa.Integer(), nullable=True),
                    sa.Column('columns_detected', sa.JSON(), nullable=True),
                    sa.Column('columns_mapped', sa.JSON(), nullable=True),
                    sa.Column('timestamp_range_start', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('timestamp_range_end', sa.DateTime(timezone=True), nullable=True),
                    sa.Column('trip_id', sa.Integer(), nullable=True),
                    sa.Column('session_id', sa.String(length=36), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('file_hash'),
                    sa.UniqueConstraint('import_code')
                    )
    op.create_table('soc_transitions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('trip_id', sa.Integer(), nullable=True),
                    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
                    sa.Column('soc_at_transition', sa.Float(), nullable=True),
                    sa.Column('ambient_temp_f', sa.Float(), nullable=True),
                    sa.Column('odometer_miles', sa.Float(), nullable=True),
                    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_soc_transitions_timestamp'), 'soc_transitions', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_soc_transitions_timestamp'), table_name='soc_transitions')
    op.drop_table('soc_transitions')
    op.drop_table('csv_imports')
    op.drop_index(op.f('ix_web_vitals_timestamp'), table_name='web_vitals')
    op.drop_index('ix_web_vitals_rating', table_name='web_vitals')
    op.drop_index('ix_web_vitals_name_timestamp', table_name='web_vitals')
    op.drop_table('web_vitals')
    op.drop_index('ix_weather_cache_lookup', table_name='weather_cache')
    op.drop_index('ix_weather_cache_fetched_at', table_name='weather_cache')
    op.drop_table('weather_cache')
    op.drop_index(op.f('ix_trips_start_time'), table_name='trips')
    op.drop_index(op.f('ix_trips_is_imported'), table_name='trips')
    op.drop_index('ix_trips_is_closed_start_time', table_name='trips')
    op.drop_index(op.f('ix_trips_is_closed'), table_name='trips')
    op.drop_index('ix_trips_gas_mode_start_time', table_name='trips')
    op.drop_index(op.f('ix_trips_gas_mode_entered'), table_name='trips')
    op.drop_index(op.f('ix_trips_deleted_at'), table_name='trips')
    op.drop_index('ix_trips_closed_deleted_time', table_name='trips')
    op.drop_table('trips')
    op.drop_table('trip_daily_stats')
    op.drop_index('ix_telemetry_session_timestamp', table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_timestamp'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_state_of_charge'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_session_id'), table_name='telemetry_raw')
    op.drop_index(op.f('ix_telemetry_raw_engine_rpm'), table_name='telemetry_raw')
    op.drop_table('telemetry_raw')
    op.drop_table('routes')
    op.drop_table('monthly_summary')
    op.drop_index('ix_maintenance_type_date', table_name='maintenance_records')
    op.drop_index(op.f('ix_maintenance_records_service_date'), table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_fuel_events_timestamp'), table_name='fuel_events')
    op.drop_table('fuel_events')
    op.drop_index(op.f('ix_charging_sessions_start_time'), table_name='charging_sessions')
    op.drop_index('ix_charging_sessions_is_complete_start_time', table_name='charging_sessions')
    op.drop_index(op.f('ix_charging_sessions_is_complete'), table_name='charging_sessions')
    op.drop_table('charging_sessions')
    op.drop_table('charging_hourly_stats')
    op.drop_index(op.f('ix_battery_health_readings_timestamp'), table_name='battery_health_readings')
    op.drop_table('battery_health_readings')
    op.drop_index(op.f('ix_battery_cell_readings_timestamp'), table_name='battery_cell_readings')
    op.drop_table('battery_cell_readings')
    op.drop_index('ix_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_ip', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
