package com.volttracker.obdpoc.ui.drive

/** Propulsion source for the moment: EV (battery) or extended-range (gas). */
enum class DriveMode { EV, GAS }

/**
 * Everything the Drive screen renders, as one immutable value.
 * Pure data — previewable and screenshot-testable with no service running.
 */
data class DriveUiState(
    val connected: Boolean = false,
    val statusLabel: String = "No adapter",
    /** Signed pack power in kW: positive = drive (discharge), negative = regen. */
    val powerKw: Double = 0.0,
    val maxDriveKw: Double = 40.0,
    val maxRegenKw: Double = 40.0,
    val speedMph: Int = 0,
    /** Recent speed samples (mph), oldest first — the hero sparkline. */
    val speedTrace: List<Float> = emptyList(),
    /** Signed pack power samples (kW) over the last minute, oldest first. */
    val powerTrace: List<Float> = emptyList(),
    /** SOC samples (%) across the session, oldest first. */
    val socTrace: List<Float> = emptyList(),
    val socPercent: Double = 0.0,
    val evRangeMiles: Double = 0.0,
    val packTempF: Int = 0,
    val packVolts: Double = 0.0,
    /** Signed pack current in A: positive = discharge, negative = charge/regen. */
    val packAmps: Double = 0.0,
    val mode: DriveMode = DriveMode.EV,
    val rpm: Int = 0,
    val auxVolts: Double = 0.0,
    val coolantF: Int = 0,
    val gpsAccuracyFt: Int? = null,
    val ambientF: Int = 0,
    val gear: String = "--",
    val motorATempF: Int = 0,
    val motorBTempF: Int = 0,
    val transTempF: Int = 0,
    val torqueNm: Int = 0,
    val oilLifePct: Int = 0,
    /** Density: false = Focus (essentials only), true = Detailed (charts + more signals). */
    val detailed: Boolean = true,
    val tripMiles: Double = 0.0,
    val tripDuration: String = "--",
    val tripMaxMph: Int = 0,
    val tripMiPerKwh: Double? = null,
) {
    companion object {
        /**
         * Sample state mirroring the browser demo stream mid-drive — used by
         * previews and the Roborazzi screenshot suite.
         */
        val demo =
            DriveUiState(
                connected = true,
                statusLabel = "Live · 1 Hz",
                powerKw = 21.4,
                speedMph = 38,
                speedTrace =
                    listOf(
                        26f,
                        29f,
                        33f,
                        36f,
                        38f,
                        41f,
                        43f,
                        42f,
                        39f,
                        34f,
                        30f,
                        27f,
                        25f,
                        27f,
                        31f,
                        35f,
                        39f,
                        42f,
                        44f,
                        43f,
                        41f,
                        38f,
                        35f,
                        33f,
                        32f,
                        34f,
                        36f,
                        38f,
                        39f,
                        38f,
                    ),
                powerTrace =
                    listOf(
                        12f,
                        15f,
                        19f,
                        23f,
                        26f,
                        22f,
                        16f,
                        7f,
                        -6f,
                        -14f,
                        -18f,
                        -9f,
                        3f,
                        11f,
                        17f,
                        22f,
                        26f,
                        28f,
                        23f,
                        17f,
                        9f,
                        -4f,
                        -12f,
                        -16f,
                        -7f,
                        5f,
                        13f,
                        18f,
                        21f,
                        21.4f,
                    ),
                socTrace =
                    listOf(
                        71f,
                        70.6f,
                        70.1f,
                        69.7f,
                        69.4f,
                        69f,
                        68.4f,
                        67.9f,
                        67.6f,
                        67.7f,
                        67.8f,
                        67.4f,
                        66.9f,
                        66.3f,
                        65.8f,
                        65.2f,
                        64.8f,
                        64.3f,
                        63.9f,
                        64f,
                        63.6f,
                        63.1f,
                        62.7f,
                        62.3f,
                        62f,
                    ),
                socPercent = 62.0,
                evRangeMiles = 26.0,
                packTempF = 73,
                packVolts = 364.0,
                packAmps = 58.8,
                mode = DriveMode.EV,
                rpm = 0,
                auxVolts = 14.2,
                coolantF = 174,
                gpsAccuracyFt = 13,
                ambientF = 68,
                gear = "D",
                motorATempF = 104,
                motorBTempF = 98,
                transTempF = 141,
                torqueNm = 118,
                oilLifePct = 87,
                tripMiles = 24.0,
                tripDuration = "1h 05m",
                tripMaxMph = 65,
                tripMiPerKwh = 4.7,
            )
    }
}
