[versions]
androidx-core = "1.18.0"
junit = "4.13.2"
json = "20260522"
robolectric = "4.16.1"
spotless = "8.5.1"

[libraries]
androidx-core = { module = "androidx.core:core", version.ref = "androidx-core" }
junit = { module = "junit:junit", version.ref = "junit" }
json = { module = "org.json:json", version.ref = "json" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }

[plugins]
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
