// Fake of the `VoltTrackerAndroid` JS bridge that the WebView normally gets
// from `MainActivity#addJavascriptInterface`. Each method here mirrors a
// `@JavascriptInterface` method on `VoltBridge.kt`. Keep this list in sync
// with that file — if Android adds or renames a method, update both places.
//
// Return values default to JSON strings (the real bridge returns Strings),
// or `undefined` for void methods. Test code can override any method with
// `vi.fn()` to assert how the dashboard calls into Android.
export function createVoltBridgeFixture(overrides = {}) {
  const stub = (returnValue) => () => returnValue;
  const voidStub = () => undefined;
  const base = {
    // String returners (real bridge returns JSON-encoded Strings).
    listDevices: stub('[]'),
    getLastDevice: stub('{}'),
    getDeviceHistory: stub('[]'),
    getAutoConnectState: stub('{"enabled":false,"available":false}'),
    getEventNotificationState: stub(
      '{"chargeComplete":true,"newDtc":true,"lowSoc":false,"lowSocThresholdPct":20,' +
        '"highPackTemp":false,"highPackTempThresholdC":45,"autoScanOnConnect":false,' +
        '"maintenanceDue":false}',
    ),
    getStorageSummary: stub('{}'),
    requestStorageSummary: stub(false),
    getStorageDetails: stub('{"storageDetails":true}'),
    requestStorageDetails: stub(false),
    exportDebugBundle: stub('{"ok":true,"path":"/tmp/debug"}'),
    getTrips: stub('[]'),
    getInsights: stub('{}'),
    getTripRoute: stub('{}'),
    getCurrentSessionRoute: stub('{}'),
    getBatterySohHistory: stub('[]'),
    requestTrips: stub(false),
    requestInsights: stub(false),
    requestTripRoute: stub(false),
    requestCurrentSessionRoute: stub(false),
    requestBatterySohHistory: stub(false),

    // void methods that hand work off to MainActivity.
    dashboardReady: voidStub,
    startupMark: voidStub,
    requestPermissions: voidStub,
    refreshDevices: voidStub,
    connect: voidStub,
    scan: voidStub,
    quickScan: voidStub,
    tpmsScan: voidStub,
    detailProbe: voidStub,
    exportDetailedSignalLog: stub('{"ok":true,"item":{"id":1}}'),
    exportDetailedSignalLogs: stub('{"ok":true,"items":[]}'),
    exportTripGpx: stub('{"ok":true,"format":"gpx","fileName":"volt-trip.gpx","bytes":256,"pointCount":3}'),
    exportTripCsv: stub('{"ok":true,"format":"csv","fileName":"volt-trip.csv","bytes":128,"pointCount":3}'),
    exportAllTripsCsv: stub('{"ok":true,"format":"csv","fileName":"volt-all-trips.csv","bytes":512,"tripCount":2,"pointCount":6}'),
    exportChargeSessionsCsv: stub('{"ok":true,"format":"csv","fileName":"volt-charges.csv","bytes":128,"chargeCount":1}'),
    shareTripCard: stub('{"ok":true,"format":"card","fileName":"volt-drive-card.png","bytes":4096,"pointCount":0}'),
    deleteDetailedSignalLog: voidStub,
    markTripNotTrip: voidStub,
    setTripLabel: voidStub,
    setTripFavorite: voidStub,
    addMaintenanceEntry: voidStub,
    getMaintenanceLog: stub('[]'),
    deleteMaintenanceEntry: voidStub,
    shareBackup: voidStub,
    shareEncryptedBackup: voidStub,
    restoreBackup: voidStub,
    restoreEncryptedBackup: voidStub,
    clearStoredData: voidStub,
    rememberDevice: voidStub,
    setAutoConnectEnabled: voidStub,
    setChargeCompleteNotify: voidStub,
    setNewDtcNotify: voidStub,
    setLowSocNotify: voidStub,
    setHighPackTempNotify: voidStub,
    setChargeTargetSoc: voidStub,
    setAutoScanOnConnect: voidStub,
    setMaintenanceDueNotify: voidStub,
    connectLast: voidStub,
    scanLast: voidStub,
    quickScanLast: voidStub,
    tpmsScanLast: voidStub,
    detailProbeLast: voidStub,
    demo: voidStub,
    disconnect: voidStub,
    logClientError: voidStub,
    clearVehicleDtcCodes: voidStub,
    openExternalSearch: voidStub,
    getRecentSessions: stub('[]'),
    forceStopPackage: stub(false),
    cancelRetry: voidStub,
    tryReconnectNow: voidStub,
    openBluetoothSettings: voidStub,
    openSetupGuide: voidStub,
    shareDiagnostics: voidStub,
    shareDiagnosticsDigest: voidStub,
    startTestConnection: voidStub,
    scheduleAdapterReadyNotify: voidStub,
    cancelAdapterReadyNotify: voidStub,
  };
  return { ...base, ...overrides };
}

// Names of every method the real VoltBridge.kt exposes via
// @JavascriptInterface. The ABI test cross-references this list with what
// VoltBridge.kt actually advertises.
export const VOLT_BRIDGE_METHODS = Object.freeze([
  'listDevices',
  'dashboardReady',
  'startupMark',
  'requestPermissions',
  'refreshDevices',
  'connect',
  'scan',
  'quickScan',
  'tpmsScan',
  'detailProbe',
  'getLastDevice',
  'getDeviceHistory',
  'getAutoConnectState',
  'getEventNotificationState',
  'setChargeCompleteNotify',
  'setNewDtcNotify',
  'setLowSocNotify',
  'setHighPackTempNotify',
  'setChargeTargetSoc',
  'setAutoScanOnConnect',
  'setMaintenanceDueNotify',
  'getStorageSummary',
  'requestStorageSummary',
  'getStorageDetails',
  'requestStorageDetails',
  'exportDebugBundle',
  'shareBackup',
  'shareEncryptedBackup',
  'restoreBackup',
  'restoreEncryptedBackup',
  'getTrips',
  'getInsights',
  'getTripRoute',
  'getCurrentSessionRoute',
  'getBatterySohHistory',
  'requestTrips',
  'requestInsights',
  'requestTripRoute',
  'requestCurrentSessionRoute',
  'requestBatterySohHistory',
  'clearStoredData',
  'rememberDevice',
  'setAutoConnectEnabled',
  'connectLast',
  'scanLast',
  'quickScanLast',
  'tpmsScanLast',
  'detailProbeLast',
  'exportDetailedSignalLog',
  'exportDetailedSignalLogs',
  'exportTripGpx',
  'exportTripCsv',
  'exportAllTripsCsv',
  'exportChargeSessionsCsv',
  'shareTripCard',
  'deleteDetailedSignalLog',
  'markTripNotTrip',
  'setTripLabel',
  'setTripFavorite',
  'addMaintenanceEntry',
  'getMaintenanceLog',
  'deleteMaintenanceEntry',
  'demo',
  'disconnect',
  'logClientError',
  'clearVehicleDtcCodes',
  'openExternalSearch',
  'getRecentSessions',
  'forceStopPackage',
  'cancelRetry',
  'tryReconnectNow',
  'openBluetoothSettings',
  'openSetupGuide',
  'shareDiagnostics',
  'shareDiagnosticsDigest',
  'startTestConnection',
  'scheduleAdapterReadyNotify',
  'cancelAdapterReadyNotify',
]);
